name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: publish to github packages
      uses: docker/build-push-action@v2
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registory: docker.pkg.github.com
        repository: ${{github.repository}}/WebApplicationDockerTest
        tags: latest , ${{github.run_number}}
        
    - name: publish to Docker hub
      uses: docker/build-push-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: knight2k21/webapplicationdockertest
        tags: latest , ${{github.run_number}}
