name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:  |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: knight2k21/webapplicationdockertesting:latest
