name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag knight2k21/webapplicationdockertesting:latest
    - name: Docker Push
      run: docker push knight2k21/webapplicationdockertesting
