name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:  |
        docker login -u knight2k21 -p knight943
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag knight2k21/webapplicationdockertesting:$(date +%s)
    - name: Docker Push
      run: docker push knight2k21/webapplicationdockertesting
